In [33]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv("HRDataset_v14.csv")

In [8]:
data

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

In [9]:
data.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Sex                             0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             207
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Sex                         311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   303 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 87.6+ KB

In [6]:
Salary = data["Salary"]
Termd = data["Termd"]
EngagementSurvey = data["EngagementSurvey"]
EmpSatisfaction = data["EmpSatisfaction"]
SpecialProjectsCount = data["SpecialProjectsCount"]
Absences = data["Absences"]

In [61]:
x = pd.concat([Termd, EngagementSurvey], axis = 1)
x = pd.concat([x, EmpSatisfaction], axis = 1)
x = pd.concat([x, SpecialProjectsCount], axis = 1)
x = pd.concat([x, Absences], axis = 1)

y = Salary

In [62]:
x.head()

   Termd  EngagementSurvey  EmpSatisfaction  SpecialProjectsCount  Absences
0      0              4.60                5                     0         1
1      1              4.96                3                     6        17
2      1              3.02                3                     0         3
3      0              4.84                5                     0        15
4      1              5.00                4                     0         2

In [76]:
sc = StandardScaler()
x = sc.fit_transform(x)

In [95]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.40, random_state = 33)

In [96]:
X_train

array([[-0.70881271, -0.64666116,  1.22202203, -0.51953795, -0.21186107],
       [-0.70881271,  0.36770929,  1.22202203, -0.51953795,  1.15725668],
       [-0.70881271, -1.39475937,  1.22202203,  2.46472096,  0.81497724],
       [ 1.41080991,  0.97633156, -0.98115972, -0.51953795,  1.15725668],
       [-0.70881271, -0.38038892, -0.98115972,  2.03839825, -0.72528022],
       [ 1.41080991,  0.87489452,  1.22202203, -0.51953795, -0.89641994],
       [-0.70881271,  1.12848713,  1.22202203, -0.51953795,  1.49953611],
       [ 1.41080991,  0.74809821,  0.12043116, -0.51953795, -0.21186107],
       [-0.70881271,  0.24091298,  1.22202203,  1.61207555, -1.06755965],
       [ 1.41080991,  0.6213019 ,  1.22202203, -0.51953795, -0.5541405 ],
       [-0.70881271,  1.12848713, -0.98115972, -0.51953795, -1.06755965],
       [ 1.41080991, -0.22823335, -0.98115972, -0.51953795, -1.23869937],
       [ 1.41080991,  1.12848713,  1.22202203, -0.51953795, -1.58097881],
       [ 1.41080991,  0.4945056 ,  1.22202203, -0.51953795, -1.40983909],
       [-0.70881271,  0.24091298, -0.98115972,  1.61207555,  1.49953611],
       [-0.70881271,  0.36770929,  1.22202203, -0.51953795, -1.58097881],
       [-0.70881271,  1.05240935, -0.98115972,  1.61207555,  1.15725668],
       [-0.70881271, -0.26627224,  1.22202203,  1.61207555, -0.21186107],
       [-0.70881271,  0.11411668, -0.98115972, -0.51953795, -1.23869937],
       [ 1.41080991,  0.24091298,  0.12043116,  2.03839825, -0.38300078],
       [ 1.41080991,  0.4945056 ,  1.22202203, -0.51953795,  1.67067583],
       [-0.70881271,  0.        ,  0.12043116,  2.03839825,  0.98611696],
       [ 1.41080991,  1.12848713, -0.98115972, -0.51953795,  0.81497724],
       [-0.70881271,  0.65934079, -0.98115972, -0.51953795, -1.40983909],
       [-0.70881271, -0.01267963,  1.22202203,  2.46472096, -1.40983909],
       [-0.70881271, -3.68977253, -0.98115972,  2.03839825, -1.40983909],
       [ 1.41080991,  0.6213019 ,  0.12043116,  1.18575285, -0.04072135],
       [-0.70881271, -0.26627224,  0.12043116, -0.51953795, -1.23869937],
       [-0.70881271, -0.01267963, -0.98115972, -0.51953795,  0.47269781],
       [-0.70881271,  0.31699077,  1.22202203, -0.51953795, -0.04072135],
       [-0.70881271, -0.90025378, -0.98115972,  2.03839825,  0.64383752],
       [-0.70881271,  0.44378707,  1.22202203,  2.03839825, -0.5541405 ],
       [-0.70881271,  0.24091298,  0.12043116, -0.51953795, -1.58097881],
       [ 1.41080991, -2.04142054, -0.98115972, -0.51953795,  0.47269781],
       [ 1.41080991, -0.17751483,  0.12043116, -0.51953795, -0.5541405 ],
       [-0.70881271,  1.12848713,  1.22202203, -0.51953795,  0.47269781],
       [-0.70881271, -0.01267963,  1.22202203, -0.51953795, -1.23869937],
       [-0.70881271,  1.12848713, -0.98115972, -0.51953795,  1.49953611],
       [-0.70881271, -0.01267963, -0.98115972, -0.51953795, -0.72528022],
       [-0.70881271, -0.22823335, -0.98115972, -0.51953795,  1.67067583],
       [-0.70881271,  0.12679631,  1.22202203, -0.51953795, -1.06755965],
       [-0.70881271, -0.13947594, -0.98115972, -0.51953795, -0.5541405 ],
       [-0.70881271,  0.11411668,  1.22202203,  1.61207555, -0.38300078],
       [-0.70881271,  1.12848713,  1.22202203,  2.03839825,  0.98611696],
       [-0.70881271, -1.35672048, -0.98115972,  1.18575285,  1.49953611],
       [-0.70881271, -1.06508898,  0.12043116,  1.61207555,  0.47269781],
       [-0.70881271, -0.48182597, -0.98115972, -0.51953795,  0.98611696],
       [-0.70881271, -0.51986486, -0.98115972, -0.51953795,  0.64383752],
       [ 1.41080991, -1.15384639, -2.0827506 , -0.51953795, -1.06755965],
       [-0.70881271, -3.23330582,  1.22202203, -0.51953795,  0.81497724],
       [-0.70881271, -1.407439  ,  1.22202203, -0.51953795,  1.15725668],
       [-0.70881271,  1.12848713,  0.12043116,  2.46472096, -0.38300078],
       [-0.70881271,  1.12848713, -0.98115972, -0.51953795, -1.40983909],
       [-0.70881271, -0.01267963,  0.12043116, -0.51953795,  0.47269781],
       [ 1.41080991,  1.12848713,  0.12043116, -0.51953795,  0.64383752],
       [-0.70881271, -0.29163151,  0.12043116, -0.51953795, -0.72528022],
       [ 1.41080991,  0.4945056 ,  0.12043116,  1.61207555, -0.38300078],
       [ 1.41080991,  0.4945056 ,  1.22202203, -0.51953795,  0.81497724],
       [-0.70881271,  0.21555372,  0.12043116,  1.61207555, -0.21186107],
       [ 1.41080991, -2.16821684,  1.22202203, -0.51953795, -1.40983909],
       [-0.70881271, -0.64666116,  1.22202203, -0.51953795, -1.06755965],
       [-0.70881271, -0.1648352 , -0.98115972, -0.51953795, -1.06755965],
       [-0.70881271,  0.6213019 ,  0.12043116, -0.51953795,  0.64383752],
       [-0.70881271,  0.4945056 , -0.98115972, -0.51953795, -0.72528022],
       [-0.70881271, -0.57058338, -0.98115972, -0.51953795,  0.81497724],
       [-0.70881271,  0.74809821, -0.98115972, -0.51953795, -1.58097881],
       [-0.70881271,  0.46914633,  1.22202203,  2.03839825, -1.06755965],
       [ 1.41080991, -1.36940011,  1.22202203, -0.51953795,  0.98611696],
       [-0.70881271,  0.11411668,  0.12043116,  2.89104366, -0.5541405 ],
       [-0.70881271, -1.53423531, -0.98115972, -0.51953795, -0.72528022],
       [-0.70881271,  0.24091298, -0.98115972, -0.51953795, -0.5541405 ],
       [-0.70881271,  0.87489452,  0.12043116, -0.51953795, -1.06755965],
       [-0.70881271,  0.24091298,  1.22202203,  2.46472096,  1.67067583],
       [-0.70881271,  0.51986486,  0.12043116, -0.51953795, -1.06755965],
       [ 1.41080991, -0.72273895,  1.22202203, -0.51953795,  0.81497724],
       [-0.70881271,  0.4945056 , -0.98115972, -0.51953795, -0.89641994],
       [ 1.41080991, -1.38207974, -0.98115972, -0.51953795, -1.23869937],
       [-0.70881271,  1.12848713,  0.12043116, -0.51953795, -0.04072135],
       [ 1.41080991,  0.24091298, -0.98115972, -0.51953795,  1.49953611],
       [-0.70881271,  0.6213019 ,  0.12043116, -0.51953795,  0.13041837],
       [ 1.41080991,  1.12848713,  1.22202203, -0.51953795,  1.15725668],
       [-0.70881271,  0.4945056 ,  0.12043116, -0.51953795, -1.58097881],
       [-0.70881271, -0.01267963, -0.98115972, -0.51953795, -0.5541405 ],
       [ 1.41080991,  0.27895187, -0.98115972,  2.46472096, -0.21186107],
       [ 1.41080991,  1.12848713,  1.22202203, -0.51953795,  0.13041837],
       [ 1.41080991,  0.11411668, -0.98115972,  1.61207555, -1.40983909],
       [-0.70881271,  1.12848713,  1.22202203,  2.03839825, -0.5541405 ],
       [-0.70881271, -0.90025378,  0.12043116, -0.51953795, -0.5541405 ],
       [-0.70881271,  0.36770929,  0.12043116,  2.03839825, -0.04072135],
       [-0.70881271, -0.19019446,  0.12043116, -0.51953795, -0.72528022],
       [-0.70881271,  0.11411668, -0.98115972, -0.51953795, -1.40983909],
       [-0.70881271, -1.16652602, -0.98115972, -0.51953795, -0.21186107],
       [-0.70881271,  1.12848713,  1.22202203, -0.51953795,  0.81497724],
       [-0.70881271,  0.6213019 , -0.98115972, -0.51953795,  1.67067583],
       [ 1.41080991,  0.06339815,  1.22202203, -0.51953795, -0.72528022],
       [-0.70881271,  0.92561304,  1.22202203, -0.51953795,  0.81497724],
       [ 1.41080991, -1.17920565,  0.12043116, -0.51953795,  0.98611696],
       [ 1.41080991,  0.68470006,  0.12043116, -0.51953795,  0.81497724],
       [-0.70881271,  1.07776861,  0.12043116,  2.03839825, -1.23869937],
       [-0.70881271,  1.12848713,  0.12043116, -0.51953795,  0.13041837],
       [-0.70881271,  1.12848713,  1.22202203, -0.51953795,  0.13041837],
       [ 1.41080991, -1.10312787, -0.98115972,  1.18575285, -0.72528022],
       [-0.70881271, -0.90025378,  1.22202203, -0.51953795,  0.81497724],
       [-0.70881271, -0.01267963,  0.12043116, -0.51953795, -0.89641994],
       [ 1.41080991, -1.407439  , -2.0827506 , -0.51953795, -0.72528022],
       [ 1.41080991, -0.96365193,  0.12043116, -0.51953795, -0.72528022],
       [-0.70881271,  0.74809821, -0.98115972,  2.03839825, -1.40983909],
       [-0.70881271, -0.01267963,  0.12043116, -0.51953795,  1.3283964 ],
       [ 1.41080991, -0.17751483,  0.12043116, -0.51953795,  0.81497724],
       [-0.70881271, -1.14116676, -0.98115972, -0.51953795, -0.5541405 ],
       [ 1.41080991, -1.22992418,  1.22202203, -0.51953795,  1.49953611],
       [-0.70881271, -1.02705008,  0.12043116, -0.51953795,  0.13041837],
       [-0.70881271,  0.11411668,  0.12043116, -0.51953795,  0.47269781],
       [-0.70881271,  1.12848713,  1.22202203,  1.61207555,  0.81497724],
       [-0.70881271,  0.24091298, -0.98115972, -0.51953795,  0.64383752],
       [-0.70881271,  1.12848713,  1.22202203, -0.51953795, -1.40983909],
       [ 1.41080991,  1.12848713,  1.22202203, -0.51953795, -1.06755965],
       [-0.70881271,  1.12848713, -0.98115972,  1.18575285, -0.89641994],
       [ 1.41080991,  0.24091298,  0.12043116, -0.51953795, -1.23869937],
       [-0.70881271,  1.12848713, -0.98115972,  2.03839825,  1.15725668],
       [-0.70881271,  0.4945056 ,  1.22202203, -0.51953795,  1.67067583],
       [-0.70881271,  0.63398153,  0.12043116,  1.61207555,  0.13041837],
       [-0.70881271, -0.05071852,  0.12043116, -0.51953795,  0.47269781],
       [ 1.41080991, -2.54860576,  1.22202203,  1.18575285,  1.49953611],
       [ 1.41080991,  0.67202043,  0.12043116, -0.51953795, -0.38300078],
       [ 1.41080991,  0.11411668,  1.22202203, -0.51953795,  0.30155809],
       [ 1.41080991,  0.4945056 , -0.98115972, -0.51953795, -0.89641994],
       [-0.70881271, -0.53254449,  1.22202203,  2.03839825,  0.81497724],
       [ 1.41080991, -0.29163151, -0.98115972,  2.46472096,  0.30155809],
       [-0.70881271,  0.01267963,  1.22202203, -0.51953795,  0.81497724],
       [-0.70881271, -1.64835199, -0.98115972, -0.51953795,  0.98611696],
       [-0.70881271,  0.6213019 ,  0.12043116, -0.51953795, -0.5541405 ],
       [ 1.41080991,  0.72273895,  0.12043116, -0.51953795,  1.67067583],
       [-0.70881271,  0.67202043,  0.12043116,  1.61207555,  0.64383752],
       [-0.70881271, -0.01267963, -0.98115972, -0.51953795,  0.13041837],
       [-0.70881271, -0.13947594,  0.12043116, -0.51953795, -0.5541405 ],
       [ 1.41080991,  0.11411668,  0.12043116, -0.51953795,  0.30155809],
       [-0.70881271,  1.12848713,  1.22202203, -0.51953795, -0.5541405 ],
       [ 1.41080991,  1.12848713, -0.98115972, -0.51953795,  1.15725668],
       [ 1.41080991, -1.30600196,  0.12043116, -0.51953795,  1.3283964 ],
       [-0.70881271,  1.12848713, -0.98115972,  0.33310745, -1.23869937],
       [-0.70881271,  1.12848713, -0.98115972, -0.51953795,  0.64383752],
       [ 1.41080991,  0.11411668,  1.22202203, -0.51953795, -0.21186107],
       [-0.70881271, -2.18089648, -0.98115972,  2.03839825,  0.47269781],
       [-0.70881271,  0.24091298, -0.98115972, -0.51953795, -1.06755965],
       [-0.70881271,  0.64666116,  0.12043116, -0.51953795, -0.38300078],
       [-0.70881271, -0.64666116,  1.22202203, -0.51953795, -1.06755965],
       [-0.70881271, -0.51986486,  1.22202203, -0.51953795,  0.81497724],
       [ 1.41080991, -2.67540207, -0.98115972, -0.51953795,  0.98611696],
       [ 1.41080991, -0.64666116, -0.98115972, -0.51953795,  0.98611696],
       [-0.70881271,  1.12848713,  0.12043116,  1.18575285, -1.23869937],
       [-0.70881271,  1.12848713,  0.12043116,  0.75943015, -1.06755965],
       [-0.70881271, -1.26796307,  1.22202203, -0.51953795, -1.06755965],
       [ 1.41080991,  1.12848713, -0.98115972, -0.51953795,  0.13041837],
       [-0.70881271,  0.4945056 ,  0.12043116, -0.51953795,  1.49953611],
       [-0.70881271, -1.01437045, -0.98115972,  2.03839825, -0.5541405 ],
       [-0.70881271,  1.12848713,  1.22202203, -0.51953795,  1.3283964 ],
       [ 1.41080991,  0.6213019 , -0.98115972,  1.18575285, -0.21186107],
       [-0.70881271, -2.76415949, -0.98115972, -0.51953795, -0.89641994],
       [-0.70881271, -0.15215557, -0.98115972, -0.51953795,  0.64383752],
       [-0.70881271,  1.12848713,  0.12043116, -0.51953795,  1.49953611],
       [-0.70881271, -1.407439  , -3.18434147, -0.51953795, -0.89641994],
       [-0.70881271,  0.74809821,  0.12043116,  1.61207555, -1.58097881],
       [-0.70881271, -2.67540207, -0.98115972, -0.51953795, -1.23869937],
       [-0.70881271,  0.31699077,  1.22202203, -0.51953795,  0.98611696],
       [ 1.41080991,  1.12848713,  0.12043116, -0.51953795,  0.98611696],
       [-0.70881271,  0.36770929, -0.98115972, -0.51953795,  0.98611696],
       [-0.70881271, -1.91462423,  0.12043116, -0.51953795, -1.06755965],
       [ 1.41080991,  0.24091298,  0.12043116, -0.51953795,  0.98611696],
       [ 1.41080991,  1.12848713, -0.98115972, -0.51953795, -0.5541405 ],
       [-0.70881271,  0.91293341, -0.98115972, -0.51953795, -0.04072135],
       [ 1.41080991,  1.12848713,  0.12043116, -0.51953795,  0.13041837],
       [-0.70881271,  0.11411668,  0.12043116, -0.51953795,  1.49953611],
       [-0.70881271, -0.77345747,  1.22202203, -0.51953795,  1.15725668],
       [-0.70881271,  0.50718523,  0.12043116, -0.51953795, -1.23869937],
       [-0.70881271,  0.4945056 ,  0.12043116, -0.51953795,  0.13041837],
       [ 1.41080991, -0.27895187,  0.12043116, -0.51953795, -0.5541405 ],
       [-0.70881271, -1.2806427 ,  1.22202203,  2.89104366,  1.49953611],
       [-0.70881271, -0.48182597, -0.98115972, -0.51953795,  1.49953611],
       [-0.70881271,  0.22823335,  1.22202203, -0.51953795,  0.13041837],
       [-0.70881271, -1.35672048, -0.98115972,  2.03839825, -1.40983909],
       [-0.70881271, -0.13947594, -0.98115972, -0.51953795,  0.30155809],
       [ 1.41080991, -0.13947594,  0.12043116, -0.51953795, -1.06755965],
       [-0.70881271, -0.40574818,  1.22202203,  1.61207555, -0.38300078],
       [ 1.41080991, -0.83685562,  0.12043116, -0.51953795, -0.89641994],
       [-0.70881271,  1.12848713, -0.98115972, -0.51953795,  0.47269781]])

In [97]:
y.head()

0     62506
1    104437
2     64955
3     64991
4     50825
Name: Salary, dtype: int64

In [98]:
linear_regression = LinearRegression()
linear_regression.fit(X_train, Y_train)

LinearRegression()

In [99]:
predict = linear_regression.predict(X_test)

In [100]:
predict

array([ 85791.05923386,  65446.99894653,  63560.14466958,  60959.1734398 ,
        84733.48358889, 101957.15249567,  98852.51215798,  59529.75514407,
        63516.59731388,  67468.64969257,  63961.58098486,  84009.35903109,
        97820.35045968,  62289.69433379,  88419.08845671,  67394.53353755,
        67975.30573236,  59055.37853979,  65479.27838204,  55482.94284571,
        62785.78174316,  65857.53526122,  66295.64504744,  59422.36749879,
        90980.9973324 ,  61677.1023598 ,  97605.7018541 ,  61030.7708433 ,
        67899.46202121,  99208.75707117,  54723.53406111,  64638.28056946,
        65048.4660534 ,  61360.32551412,  64238.40479084,  61935.7674409 ,
        65862.2135376 ,  64047.24090512,  61773.20516496,  63419.50245398,
        70945.51735165,  60209.16581551,  60233.32038641,  65857.53526122,
        55932.97254377,  58609.59514939,  68172.77502093,  63934.5229918 ,
        64418.9081405 ,  61958.06364785,  68534.86474116,  64821.5119259 ,
        63062.78096451,  68070.06565203,  92375.90262151,  61923.16503114,
        96953.5245911 ,  90426.3089353 ,  61981.24308395,  67979.18428932,
        63062.78096451,  64330.82137436,  91984.04288192,  61148.80210471,
        69092.93501561,  64980.65530122,  55541.82901387,  64726.92742161,
        67794.32580643,  67107.24992672,  66888.24524845,  64784.07763772,
        62465.71174238,  66290.79135568,  65083.1723348 ,  97036.45650457,
        64815.01418774,  60637.55129827,  64238.40479084,  61280.71207159,
        62264.08805181,  65918.93178498,  59355.44837167,  91610.60160394,
        63015.63929282,  60071.92558059,  63617.77146197,  67221.31072553,
        67957.17232333,  67864.75573982,  60060.48224503,  68049.50539712,
        63135.72125351,  61570.68984932,  61355.563728  ,  65439.41724799,
        66615.04107432,  60400.22087565,  63679.16798573,  61296.59405012,
        76179.04822506,  63697.3849045 ,  85879.32141537,  69053.07388155,
        65400.03269021,  64788.32394537,  63586.83491195,  65659.69822196,
        80707.71000064,  68010.72822345,  63723.27542744,  58519.60541175,
        86108.00403847,  63006.06271713,  59682.3172715 ,  55116.23812768,
        61671.94750714,  58041.43376024,  68691.6741157 ,  59891.3303253 ,
        67972.51113579,  63600.00580363,  62948.7201657 ,  98493.45572828,
        63188.66976952])

In [101]:
from sklearn.metrics import accuracy_score, r2_score

In [102]:
test_data_r2_score = r2_score(Y_test, predict)

In [103]:
test_data_r2_score

0.38335228744982774

In [104]:
input_data1 = (0, 4.60, 5, 0, 1)
input_data2 = (1,85,66,29,0,26.6,0.351,31)

#Changing Input Data As Numpy Array
input_data_array = np.asarray(input_data1)

# Reshape the data as we are predicting for only one instance
input_data_reshape = input_data_array.reshape(1,-1)

# Standardize the data
std_data = sc.transform(input_data_reshape)

# Prediction
Predict = linear_regression.predict(std_data)
print("Predict: ", Predict)
print("y: ", y[0])

Predict:  [61570.68984932]
y:  62506